defaults:
  - ../config/traj_envs_gem_math@_here_

hydra:
  run:
    dir: .
  output_subdir: null

exp_name: "agentic_pipeline"
seed: 42
base_dir: ./qwen3-8B-${now:%Y%m%d_%H%M%S} 
logging_dir: ${base_dir}/logs
output_dir: ${base_dir}/output
render_save_dir: ${base_dir}/render
system_envs:
  USE_MODELSCOPE: '0'

#track_with: wandb
#tracker_kwargs:
#  api_key:
#  project: roll-agentic
#  name: ${exp_name}_sokoban
#  notes: "agentic_pipeline"
#  tags:
#    - agentic
#    - roll
#    - baseline

track_with: tensorboard
tracker_kwargs:
  log_dir: ${base_dir}/tensorboard


checkpoint_config:
  type: file_system
  output_dir: ./ckpt_qwen3-8B-${now:%Y%m%d_%H%M%S}

num_gpus_per_node: 4

max_steps: 1024
save_steps: 10000
logging_steps: 1
eval_steps: 10
resume_from_checkpoint: false
enable_migration: false

rollout_batch_size: 128
val_batch_size: 128
sequence_length: 4096

advantage_clip: 20
ppo_epochs: 1
adv_estimator: "reinforce"

#pg_clip: 0.1
#dual_clip_loss: True
init_kl_coef: 0.0
whiten_advantages: true
entropy_loss_coef: 0
max_grad_norm: 1.0


pretrain: Qwen/Qwen3-8B
reward_pretrain: Qwen/Qwen3-8B

actor_train:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: false
    dtype: bf16
    model_type: ~
  training_args:
    learning_rate: 1.0e-6
    weight_decay: 0
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 8
    warmup_steps: 10
    lr_scheduler_type: cosine
  strategy_args:
#    strategy_name: deepspeed_train
#    strategy_config: ${deepspeed_zero3}
    strategy_name: megatron_train
    strategy_config:
      tensor_model_parallel_size: 4
      pipeline_model_parallel_size: 1
      expert_model_parallel_size: 1
      use_distributed_optimizer: true
      recompute_granularity: full
  device_mapping: list(range(0,8))
  device_affinity: 'NVIDIA L20X'
  num_gpus_per_node: 8
  infer_batch_size: 2

actor_infer:
  model_args:
    disable_gradient_checkpointing: true
    dtype: bf16
  generating_args:
    max_new_tokens: ${max_tokens_per_step} # single-turn response length
    top_p: 0.99
    top_k: 100
    num_beams: 1
    temperature: 0.99
    num_return_sequences: 1
  strategy_args:
    strategy_name: vllm
    strategy_config:
      gpu_memory_utilization: 0.8
      enforce_eager: true
      block_size: 16
      load_format: auto
  device_mapping: list(range(0,8))
  device_affinity: 'NVIDIA H20'
  num_gpus_per_node: 8

reference:
  model_args:
    attn_implementation: fa2
    disable_gradient_checkpointing: true
    dtype: bf16
    model_type: ~
  strategy_args:
    strategy_name: hf_infer
    strategy_config: ~
  device_mapping: list(range(0,8))
  infer_batch_size: 2
  device_affinity: 'NVIDIA L20X'
  num_gpus_per_node: 8

reward_normalization:
  grouping: batch # 可以tags(env_type)/traj_group_id(group)/batch(rollout_batch)... group_by计算reward/adv
  method: identity # asym_clip / identity / mean_std

train_env_manager:
  max_env_num_per_worker: 16
  num_env_groups: 32
  # under the same group, the env config and env seed are ensured to be equal
  group_size: 1
  tags: [Orz57K]
  num_groups_partition: [32] # If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation

val_env_manager:
  max_env_num_per_worker: 32
  num_env_groups: 32
  group_size: 1 # should be set to 1 because val temperature is set to 0 and same prompt leads to same output
  tags: [Orz57K]
  num_groups_partition: [32] # TODO: If not set, all env names divide nums equally. Under the same group, the env config and env seed (prompt) are equal in each generation


# Here, you can override variables defined in the imported envs. max_tokens_per_step: 128 in custom_env.SimpleSokoban, here replaced by 64
max_tokens_per_step: 4096

custom_envs:
  Orz57K:
    ${gem_math.Orz57K}
  Orz57K_with_python_code:
    ${gem_math.Orz57K_with_python_code}

